### ISSUE TITLE
adding parameters?

### ISSUE THREAD

**Issue by t-readyroc** [dgutierrez1287/puppet-centrify#1]
Hey Diego - trying to get in touch - I was wondering how I would go about adding parameters to the module?  specifically, I'd like to add auto.schema.private.group & auto.schema.primary.gid.

Would I, for instance, just add private_group & primary_gid to the appropriate sections in params.pp & init.pp?

**Comment by dgutierrez1287** [comment]
Are those for the free or full versions of centrify? The reason I ask is I haven't been able to test this module for the full versions of centrify only the free version. I fully welcome pull requests to fix issues with the module, If you would like to submit one for this fix. It should be just adding the parameters to the params and then inheriting the params in the init.pp (just like the other variables are, also you may need to edit the templates if those variables are used in any of the centrify config files, since they weren't part of the module before.

**Comment by t-readyroc** [comment]
This is for the free version of centrifydc.  It has been working beautifully as-is for a few months now; we just need those additional parameters to be configurable.  I'm  a complete puppet novice, but I do know those variables are in the default centrifydc.conf file (& I just found that basically mirrored in your centrifydc_config.erb).  I did not know to look into the templates dir, if that gives you any idea of where I'm coming from... heh.

**Comment by dgutierrez1287** [comment]
I should be able to make this change easily and cut a new release this weekend, I wanted to add a couple of parameters anyway to handle the auto join that the module does. I'll let you know when I have made the updates but it shouldn't take me that long.

**Comment by t-readyroc** [comment]
Wow.  Awesome.  Thanks.

**Comment by dgutierrez1287** [comment]
I cut the 0.1.1 release, this adds the ability to set the params you need and also adds the ability to set if the server will autojoin to the domain or not. Please let me know if this does not work for you.
